# configuration for a Xiao ESP32-S3 module

esphome:
  name: "tfagateway-s3"
  friendly_name: "TFA-Gateway"
  comment: "Author KHit6 (khit6@gmx.net)"
  project:
    name: "KHit6.tfagateway"
    version: "3.0.0"
  includes:
    - tfa_30_32xx.h
    - bit_util.h
    - tfa_30_32xx.cpp
    - bit_util.cpp
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

substitutions:
  TIMEOUT: 180s
  RX_PIN: GPIO09
  TX_PIN: GPIO01
  LED_PIN: GPIO6

packages:
  - !include common.yaml

